services:
  - type: web
    name: clothing-manager
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask db upgrade && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: FLASK_APP
        value: app.py
databases:
  - name: clothing-manager-db
    databaseName: clothing_manager
    user: clothing_manager_user