"""Add season and gender to products

Revision ID: 3730d2082d65
Revises: 
Create Date: 2025-07-14 06:13:16.693418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3730d2082d65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('season')

    # ### end Alembic commands ###
